#ifndef CPEG_TOKENMAP_H
#define CPEG_TOKENMAP_H

#define T_ENDMARKER 1  // ENDMARKER
#define T_NEWLINE 2  // NEWLINE
#define T_NAME 3  // NAME
#define T_NUMBER 4  // NUMBER
#define T_STRING 5  // STRING
#define T_OP_DOT 6  // .
#define T_OP_COMMA 7  // ,
#define T_OP_ASSIGN 8  // =
#define T_OP_COLON 9  // :
#define T_OP_TERNERY 10  // ?
#define T_OP_NOT 11  // !
#define T_OP_SEMICOLON 12  // ;
#define T_OP_LPAR 13  // (
#define T_OP_RPAR 14  // )
#define T_OP_LBRACE 15  // {
#define T_OP_RBRACE 16  // }
#define T_OP_LSQB 17  // [
#define T_OP_RSQB 18  // ]
#define T_OP_LESS 19  // <
#define T_OP_GREATER 20  // >
#define T_OP_PLUS 21  // +
#define T_OP_MINUS 22  // -
#define T_OP_TIMES 23  // *
#define T_OP_DIV 24  // /
#define T_OP_MODULUS 25  // %
#define T_OP_MATRIX_TIMES 26  // @
#define T_OP_BIT_OR 27  // |
#define T_OP_BIT_AND 28  // &
#define T_OP_BIT_NOT 29  // ~
#define T_OP_BIT_XOR 30  // ^
#define T_OP_EQUAL 31  // ==
#define T_OP_NEQUAL 32  // !=
#define T_OP_LESS_EQUAL 33  // <=
#define T_OP_MORE_EQUAL 34  // >=
#define T_OP_PIPE 35  // ->
#define T_OP_ASGN_EXPR 36  // :=
#define T_OP_FLOOR_DIV 37  // //
#define T_OP_POWER 38  // **
#define T_OP_PLUS_ASSIGN 39  // +=
#define T_OP_MINUS_ASSIGN 40  // -=
#define T_OP_TIMES_ASSIGN 41  // *=
#define T_OP_DIV_ASSIGN 42  // /=
#define T_OP_MODULUS_ASSIGN 43  // %=
#define T_OP_MATRIX_TIMES_ASSIGN 44  // @=
#define T_OP_BIT_OR_ASSIGN 45  // |=
#define T_OP_BIT_AND_ASSIGN 46  // &=
#define T_OP_BIT_XOR_ASSIGN 47  // ^=
#define T_OP_LSHIFT 48  // <<
#define T_OP_RSHIFT 49  // >>
#define T_OP_FLOOR_DIV_ASSIGN 50  // //=
#define T_OP_POWER_ASSIGN 51  // **=
#define T_OP_LSHIFT_ASSIGN 52  // <<=
#define T_OP_RSHIFT_ASSIGN 53  // >>=
#define T_RETURN 54  // return
#define T_NONLOCAL 55  // nonlocal
#define T_IF 56  // if
#define T_ELIF 57  // elif
#define T_ELSE 58  // else
#define T_AND 59  // and
#define T_OR 60  // or
#define T_NOT 61  // not
#define T_IS 62  // is
#define T_IN 63  // in
#define T_PASS 64  // pass
#define T_AS 65  // as
#define T_FROM 66  // from
#define T_IMPORT 67  // import
#define T_WITH 68  // with
#define T_ASYNC 69  // async
#define T_AWAIT 70  // await
#define T_WHILE 71  // while
#define T_FOR 72  // for
#define T_CONTINUE 73  // continue
#define T_BREAK 74  // break
#define T_TRY 75  // try
#define T_EXCEPT 76  // except
#define T_FINALLY 77  // finally
#define T_RAISE 78  // raise
#define T_DEL 79  // del
#define T_ASSERT 80  // assert
#define T_NONE 81  // None
#define T_TRUE 82  // True
#define T_FALSE 83  // False
#endif //CPEG_TOKENMAP_H